volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: andos12/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: andos12/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/app/staticfiles

  gateway:
    image: andos12/kittygram_gateway:latest
    env_file: .env
    volumes:
      - static:/app/staticfiles
      - media:/app/media 
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend