volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/cats/backend_static
      - media:/cats/backend_media
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/app/build
  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/mediafiles
    ports:
      - '80:80'
      - '443:443'