server {
  listen 80;
  index index.html;
  server_tokens off;

  location /api/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:9000/api/;
  }
  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:9000/admin/;
  }
  location /media/ {
    alias /media/;
  }
  
  location / {
    alias /static/frontend/;
    try_files $uri $uri/ /index.html;
  }

  location /static/frontend/ {
    alias /static/frontend/;
  }

  location /static/backend/ {
    alias /static/backend/;
  }
}