server {
  listen 80;
  server_tokens off;

  # Проксирование запросов к API
  location /api/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:9000/api/;
  }

  # Проксирование запросов к админке
  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:9000/admin/;
  }

  # Обслуживание медиафайлов
  location /media/ {
    root /;
  }

  # Обслуживание статических файлов бэкенда
  location /static/ {
    root /;
  }

  # Обслуживание фронтенда
  location / {
    root /static/frontend;
    try_files $uri $uri/ /index.html;
  }
}